# 应用服务 WEB 访问端口
server:
  port: 8081

# 应用名称
spring:
  application:
    name: huangrx-redis
  redis:
    # redis数据库索引 （默认为0）
    database: 0
    # redis所在服务器地址
    host: localhost
    # redis所在服务器端口
    port: 6379
    # redis连接超时时间（毫秒）
    timeout: 0
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait: -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1



